<?php

return [
    'db' => [
        'db_host' => 'db',
        'db_name' => 'yllusion-portal',
        'db_user' => 'root',
        'db_pass' => 'root',
        'db_port' => '3306'
    ],
    'default_page' => 'home',
    'views' => [
        'dashboard' => [
            'file' => 'dashboard.php',
            'urlPath' => ['/dashboard'],
            'path' => '/../views/users/dashboard.php',
            'route' => '/../views/layoutdaisy.php',
            'title' => 'Tableau de bord',
            'method' => ['GET', 'POST'],
            'protected' => true,
            'needToBeAdmin' => false,
        ],
        'register' => [
            'file' => 'register.php',
            'urlPath' => ['/register'],
            'path' => '/../views/users/register.php',
            'route' => '/../views/layoutdaisy.php',
            'title' => 'Enregistrement',
            'method' => ['GET', 'POST'],
            'protected' => false,
            'needToBeAdmin' => false,
        ],
        'login' => [
            'file' => 'login.php',
            'urlPath' => ['/login'],
            'path' => '/../views/users/login.php',
            'route' => '/../views/layout.php',
            'title' => 'Connexion',
            'method' => ['GET', 'POST'],
            'protected' => false,
            'needToBeAdmin' => false,
        ],
        'logout' => [
            'file' => 'logout.php',
            'urlPath' => ['/logout'],
            'path' => '/../views/users/logout.php',
            'route' => '/../views/users/logout.php',
            'title' => 'Déconnexion',
            'method' => ['GET'],
            'protected' => true,
            'needToBeAdmin' => false,
        ],
        'allLogin'=> [
            'file' => 'allLogin.php',
            'urlPath'=> ['/allLogin'],
            'path' => '/../views/users/allLogin.php',
            'route' => '/../views/layout.php',
            'title' => 'Les connexions',
            'method' => ['GET', 'POST'],
            'protected' => false,
            'needToBeAdmin' => false,
        ],
        'home'=> [
            'file' => 'home.php',
            'urlPath'=> ['/home', '/'],
            'path' => '/../views/root/home.php',
            'route' => '/../views/layout.php',
            'title' => 'Les connexions',
            'method' => ['GET', 'POST'],
            'protected' => true,
            'needToBeAdmin' => false,
        ],
        'resume'=> [
            'file' => 'resume.php',
            'urlPath'=> ['/resume'],
            'path' => '/../views/cv/resume.php',
            'route' => '/../views/layout.php',
            'title' => 'CV Maker',
            'method' => ['GET','POST'],
            'protected' => true,
            'needToBeAdmin' => false,
        ],
        'listUsers'=> [
            'file' => 'users.php',
            'urlPath'=> ['/users'],
            'path' => '/../views/users/users.php',
            'route' => '/../views/layout.php',
            'title' => 'List Users',
            'method' => ['GET','POST'],
            'protected' => true,
            'needToBeAdmin' => false,
        ],
        'profil'=> [
            'file' => 'profil.php',
            'urlPath'=> ['/profil'],
            'path' => '/../views/users/profil.php',
            'route' => '/../views/layout.php',
            'title' => 'Profil',
            'method' => ['GET','POST'],
            'protected' => true,
            'needToBeAdmin' => false,
        ],
        'userPage'=> [
            'file' => 'userPage.php',
            'urlPath'=> ['/userPage'],
            'path' => '/../views/users/userPage.php',
            'route' => '/../views/layout.php',
            'title' => 'Your Page',
            'method' => ['GET','POST'],
            'protected' => true,
            'needToBeAdmin' => false,
        ],
        'panelAdmin'=> [
            'file' => 'panelAdmin.php',
            'urlPath'=> ['/panelAdmin'],
            'path' => '/../views/users/panelAdmin.php',
            'route' => '/../views/layout.php',
            'title' => 'Panel Admin',
            'method' => ['GET','POST'],
            'protected' => true,
            'needToBeAdmin' => true,
        ],
        'downloadResume'=> [
            'file' => 'downloadResume.php',
            'urlPath'=> ['/downloadResume'],
            'path' => '/../views/cv/downloadResume.php',
            'route' => '/../views/layout.php',
            'title' => 'Panel Admin',
            'method' => ['GET', 'POST'],
            'protected' => true,
            'needToBeAdmin' => true,
        ],
        'resumeView'=> [
            'file' => 'resumeView.php',
            'urlPath'=> ['/resumeView'],
            'path' => '/../views/cv/resumeView.php',
            'route' => '/../views/layout.php',
            'title' => 'Panel Admin',
            'method' => ['POST'],
            'protected' => true,
            'needToBeAdmin' => true,
        ],
        'editResume'=> [
            'file' => 'editResume.php',
            'urlPath'=> ['/editResume'],
            'path' => '/../views/cv/editResume.php',
            'route' => '/../views/layout.php',
            'title' => 'Panel Admin',
            'method' => ['POST'],
            'protected' => true,
            'needToBeAdmin' => true,
        ],
        '404' => [
            'file' => '404.php',
            'urlPath' => ['/404'],
            'path' => '/../views/root/404.php',
            'route' => '/../views/layout.php',
            'title' => 'Page non trouvée',
            'method' => ['GET'],
            'protected' => false,
            'needToBeAdmin' => false,
        ]
    ]
];